### ISSUE TITLE
`Http` prefix in interface name

### ISSUE THREAD

**Issue by mdrost** [php-http/fig-standards#38]
If interface is already in namespace `Psr\Http` and no interface from `Psr\Http\Message` uses `Http` prefix then why `HttpClient` instead of just `Client`?

**Comment by sagikazarmark** [comment]
Sounds good to me

**Comment by WyriHaximus** [comment]
Sounds good to me as wel 👍

**Comment by dbu** [comment]
seems to be correct to drop the prefix. if i have several layer of clients in the same code, i should alias them to HttpClient and ApiClient (or more specific) in the `use` statements. :+1:

**Comment by dbu** [comment]
@mdrost want to do such a pull request? looks like we all agree on this one.

**Comment by mdrost** [comment]
What about prefix in `HttpException`?

**Comment by dbu** [comment]
i'd keep that prefix because it is explicitly about http. (there is another
discussion whether to completely drop that class, but lets not mix the
discussions)

Am 07.09.2017 7:14 nachm. schrieb "Mateusz Drost" <notifications@github.com
>:

What about prefix in HttpException?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/php-http/fig-standards/issues/38#issuecomment-327865166>,
or mute the thread

**Comment by Nyholm** [comment]
Closed by #42,
